src/App.js
src/pages/MyPage.js

- MainPage 임포트 추가
- MyPage 컴포넌트 임포트하는 경로 수정

[Fix] MainPage 임포트

---

src/pages/MyPage.js

[Chore] Admin 컴포넌트 주석 처리

---

src/components/_common/Booth.js
src/components/_common/Concert.js
src/components/_common/Menu.js
src/components/mypage/IsTfAdmin.js
src/pages/MyPage.js

[Fix] 컴포넌트 오류 해결 및 네비게이트 

---

src/components/Detail/DetailCover.js
src/pages/BoothDetailPage.js
src/pages/PerfDetailPage.js
src/pages/TrashBinPage.js

- 상세페이지 사이드 바 연결
- 상세페이지 스크롤 맨 위로 설정

[Feature] 상세페이지 사이드바 연결 

---

src/components/EditPage/EditBooth.js
src/components/EditPage/EditMenuDetail.js
src/pages/BoothDetailPage.js
src/pages/PerfDetailPage.js

컴파일 오류 해결
- 햄메뉴 임포트 재설정
- useNavigate 임포트 오류 해결

[Fix] 임포트 재설정

---

package-lock.json
package.json
src/App.js
src/_mock/makersData.js
src/components/MakersPage/Team.js
src/components/_common/TopBar.js
src/pages/MakersPage.js

TopBar 컴포넌트 기본 설정을 바꿨습니다! 
돋보기 아이콘 쓰시는 분들 
``` showSearch={true} ```
로 설정해주세요~

[Fix} import 정리 + 데이터 정리

---

src/components/MainPage/HamMenu.js
src/components/SignupPage/CommonModal.js
src/components/_common/TopBar.js
src/pages/BoothListPage.js
src/pages/MyPage.js
src/pages/PerfListPage.js
src/pages/SignupPage.js

사이드바에서 화면 이동시 스크롤 안되는 문제 해결
각 페이지에서 사이드바 상위에 주어진 padding 설정 구조 변경으로 해결
그 외 자잘한 내용들을 수정했습니다...

[Fix] 사이드바 스크롤 + padding 수정

---

src/pages/MainPage.js

[Fix] 메인페이지 탑 바 -> 마이페이지 이동 연결

---

src/pages/MyPage.js

Fix: 마이페이지 css 오류 해결

---

package-lock.json
package.json
src/api/booth.js
src/api/http.js
src/components/Detail/BoothMenu.js
src/components/Detail/DetailCover.js
src/components/Detail/DetailInfo.js
src/components/Detail/DetailReview.js
src/components/Detail/DetailTitle.js
src/pages/BoothDetailPage.js
src/pages/PerfDetailPage.js

[Feat] API 연결 세팅

---

src/_mock/tableData.js
src/components/MainPage/About.js
src/components/MainPage/HamMenu.js
src/components/MainPage/PerfPlan.js
src/components/MainPage/PerfPlanFilter.js
src/components/MainPage/PerfPlanTable.js
src/pages/MainPage.js

-공연일정표 완성
-이대 멋사 바로가기 링크 연결
-소소한 css 수정

[Feature] 공연일정표 완성

---

src/api/user.js
src/components/SignupPage/CompleteModal.js
src/pages/LoginPage.js
src/pages/SignupPage.js
src/redux/store.js

말 그대로 로그인/회원가입 페이지 API 연결을 끝냈습니다~!
redux 설정도 제가 살필 수 있는 한에서는 다 끝냈습니다.
```
PostLogin(username, password)
.then((data) => {
const token = data.data.access_token;
window.localStorage.setItem("token", JSON.stringify(token));
navigate("/");
})
.catch((error) => {
// 에러에 따라 다른 경고 문구 출력
let type = error.data.non_field_errors;
type
? type == "잘못된 비밀번호입니다."
? alert("비밀번호를 확인해주세요.")
: alert(type)
: alert("아이디와 비밀번호를 모두 입력해주세요.");
});
```
api 폴더에서 받아오실 때는 바로 함수만 작성해도 되더라구요!
괜히 try/catch 괄호 열고 그랬어서 저렇게 쓰면 될 것 같아서 공유해봅니다..^^
보시면 아시다시피 token 이름으로 localstorage에 올려놔서 이제 isLogin도 정상적으로 작동할 겁니다!

[Feat] 로그인/회원가입 페이지 API 연결 + redux 설정

---

src/api/booth.js
src/api/user.js
src/components/Detail/BoothMenu.js
src/components/Detail/DetailInfo.js
src/components/Detail/DetailReview.js
src/components/Detail/DetailTitle.js
src/components/Detail/ReviewBox.js
src/pages/BoothDetailPage.js
src/pages/LoginPage.js
src/pages/PerfDetailPage.js

- 상세페이지 API 연결 (상세 데이터, 부스/메뉴 좋아요 여부 변경, 방명록 작성/삭제)
- 프로필 조회 API 연결
- 상세페이지 시간 형태 로직 수정
프로필 조회 API 연결해서 데이터 redux에 저장하는 로직 작성해놨으니 필요한 페이지에서 가져다 쓰세요!
(함수를 가져다 쓰는 게 아니라 redux에 저장되어 있는 정보 꺼내서 쓰기)

[Feat] 상세페이지 API 연결 및 프로필 조회 로직 작성

---

src/api/booth.js

[Feat] Booth.js 수정 추가

---

src/api/user.js
src/components/Detail/BoothMenu.js
src/components/Detail/DetailReview.js
src/components/Detail/DetailTitle.js
src/pages/BoothDetailPage.js
src/pages/MyPage.js
src/pages/PerfDetailPage.js

- 상세페이지 로그인되어 있을 때만 방명록 작성, 부스/메뉴 좋아요 할 수 있게 수정
- 마이페이지 로그아웃 함수 호출
- 로그아웃 함수 수정
로그아웃 함수 주석처리한 부분 있습니다!
마이페이지에서 로그아웃 눌렀을 때 마이페이지 파일에서는 로그인 페이지로 가는 걸로 되어 있고
로그아웃 함수에는 메인페이지로 가게 되어 있더라고요 그래서 일단 주석 처리해놨고
alert 띄우는 것도 문구가 적절해보이진 않아서 일단 주석 처리 했습니다.

[Feat] 상세페이지 로그인 여부 관리

---

src/api/booth.js
src/api/tf.js
src/components/Notice/NoticeList.js
src/pages/NoticeDetailPage.js
src/pages/NoticePage.js
src/pages/NoticeWritePage.js

tf 공지사항 목록 조회, 상세 조회, 작성 api 연결
부스/공연 목록 페이지는 연결은 해뒀지만 500 에러가 뜨는 상태입니당..!
아마 url 파라미터 주는 데에서 문제가 있는 것 같아서 필터링에 조건 달거나 좀 더 수정이 필요할 듯해욥

[Feature] tf 공지사항 목록 조회, 상세 조회, 작성 api 연결

---

src/api/tf.js
src/pages/NoticeDetailPage.js
src/pages/NoticeEditPage.js

tf 공지사항 삭제, 수정 api 연결
연결은 해뒀지만 tf 계정으로 tf 계정일 때만 뜨는 버튼 잘 나오는지와 연결 잘 돌아가는지 확인 필요합니다!

[Feature] tf 공지사항 삭제, 수정 api 연결

---

src/api/user.js
src/components/MainPage/HamMenu.js
src/pages/LoginPage.js
src/pages/MainPage.js

- 프로필 조회 에러 해결 
- 프로필 조회 함수 로직 수정

[Fix] 프로필 조회 에러 해결

---

src/api/booth.js
src/components/Detail/DetailInfo.js
src/components/ListPage/BoothFilter.js
src/pages/BoothListPage.js
src/pages/MyPage.js

- 부스 목록 조회 API 함수 로직 수정
- 부스 목록 조회 API 함수 로직 수정
이 로직 참고해서 공연 목록 조회, 마이페이지 수정해주세요

[Fix] 부스 목록 조회 API 함수 로직 수정

---

src/components/ListPage/PerfFilter.js
src/pages/BoothListPage.js
src/pages/PerfListPage.js

[fix] 공연 목록 페이지 api 로직 수정

---

src/components/MainPage/EventContent.js
src/components/MainPage/HamMenu.js

메인페이지 텍스트 위치 수정
햄버거바 이미지 다시 export -> 아이콘 자체를 다운받으려니까 자꾸 export failed가 뜨고, 그룹으로 export 해야 잘 다운받아짐.. 뭐지.. 자꾸 이미지 깨지는 게 아이콘 자체의 크기 문제 같기도 하고..
햄버거바 요소들 위치 조정 (그리드 gap&margin 수정)

[Chore] 메인&햄버거메뉴 css 수정

---

src/api/booth.js
src/components/Detail/DetailInfo.js
src/components/ListPage/BoothFilter.js
src/components/ListPage/PerfFilter.js
src/pages/MyPage.js

- 부스/공연 목록 필터링 에러 해결
- 부스/공연 목록 필터링 에러 해결
명세서에 예시 써주신 것처럼 파라미터에 따라 url 바뀌게 작성해야 돼요!
목록 필터링은 수정해놨으니 마이페이지만 수정해주세요.

[Fix] 부스/공연 목록 필터링 에러 해결

---

src/pages/NoticeDetailPage.js
src/pages/NoticeEditPage.js
src/pages/NoticePage.js
src/pages/NoticeWritePage.js

[Chore] 공지사항 페이지 사이드바 간격 수정

---

src/pages/BoothListPage.js
src/pages/PerfListPage.js

[Chore] 목록 페이지 최소 높이 설정

---

src/components/MainPage/HamMenu.js
src/pages/MainPage.js

[Chore] 햄버거바 스타일 수정

---

src/api/user.js
src/pages/LoginPage.js
src/pages/SignupPage.js

토큰 만료시 로그아웃되도록 로직 구현했습니다.
이유는 모르겠지만.... 계속 만료된 토큰이라고 뜨다가 npm start 다시 했더니 되는 기적이 발생했습니다....
이렇게 해결해도 되나 싶긴 하지만 해결이 되었음에 감사하며 PR 날립니다🥲
프론트 짱이라는 말을 살포시 전해봅니다...💚

[Feat] 토큰 만료시 로그아웃 로직 구현

---

src/api/booth.js
src/pages/BoothSearchPage.js

- 검색 결과 안 뜨는 문제 해결
- 검색 API 연결 수정

[Fix] 검색 API 연결 수정

---

src/api/http.js
src/api/user.js
src/pages/LoginPage.js

토큰 업로드에 있었던 문제를... 데이터 형식을 바꿔서 해결했습니다.
이 방법이 맞는지를 모르겠습니다.......ㅎ
토큰 저장 방식이 바뀐 것으로 추정되어 http 수정하였습니다.
토큰에 access token 이외에 다른 것이 들어간 문제도 수정했습니다.

[Fix] token 관련 이슈 해결

---

src/api/tf.js
src/pages/LoginPage.js

[Fix] 페이지 리로드 설정

---

package-lock.json
package.json
src/components/Detail/BoothMenu.js
src/components/Detail/DetailCover.js
src/components/Detail/DetailTitle.js
src/components/Detail/ReviewBox.js
src/components/Detail/SectionExport.js
src/components/MainPage/AdModal.js
src/components/MainPage/PerfPlan.js
src/components/SignupPage/CommonModal.js
src/components/SignupPage/CompleteModal.js
src/components/_common/Booth.js
src/components/_common/Concert.js
src/components/_common/Menu.js
src/pages/LoginPage.js
src/pages/MakersPage.js
src/pages/MyPage.js

[style] 필요없는 콘솔, 주석, 라이브러리 제거

---

src/components/_common/Booth.js
src/components/_common/Concert.js
src/components/_common/Menu.js

부스, 공연, 메뉴 컴포넌트의 비건/휠체어 가능 태그 css 수정

[Chore] 부스,공연,메뉴 컴포넌트 css 수정
